// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using SpecPour.Modules.Ingredients.Infrastructure;

#nullable disable

namespace SpecPour.Modules.Ingredients.Infrastructure.Migrations
{
    [DbContext(typeof(IngredientsDbContext))]
    [Migration("20260711183259_InitialIngredients")]
    partial class InitialIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ingredients")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpecPour.BuildingBlocks.Events.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "outbox", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Ingredients.Domain.Allergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayNameKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Allergens", "ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201"),
                            DisplayNameKey = "allergen.egg",
                            Key = "egg"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000202"),
                            DisplayNameKey = "allergen.dairy",
                            Key = "dairy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000203"),
                            DisplayNameKey = "allergen.treeNut",
                            Key = "treeNut"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000204"),
                            DisplayNameKey = "allergen.peanut",
                            Key = "peanut"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000205"),
                            DisplayNameKey = "allergen.gluten",
                            Key = "gluten"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000206"),
                            DisplayNameKey = "allergen.sulfites",
                            Key = "sulfites"
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Ingredients.Domain.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefiningRecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LibraryScope")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("specpour_immutable_to_tsvector_english(coalesce(\"Name\", ''))", true);

                    b.Property<TimeSpan?>("ShelfLife")
                        .HasColumnType("interval");

                    b.PrimitiveCollection<string[]>("Sources")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("StorageInstructions")
                        .HasColumnType("text");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.Property<decimal?>("YieldQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("YieldUnit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.ToTable("Ingredients", "ingredients");
                });

            modelBuilder.Entity("SpecPour.Modules.Ingredients.Domain.IngredientAllergen", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllergenId")
                        .HasColumnType("uuid");

                    b.Property<int>("Certainty")
                        .HasColumnType("integer");

                    b.HasKey("IngredientId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("IngredientAllergens", "ingredients");
                });

            modelBuilder.Entity("SpecPour.Modules.Ingredients.Domain.IngredientCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.ToTable("IngredientCategories", "ingredients");
                });

            modelBuilder.Entity("SpecPour.Modules.Ingredients.Domain.SubstitutionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromIngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuitabilityNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToIngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToIngredientId");

                    b.HasIndex("FromIngredientId", "ToIngredientId")
                        .IsUnique();

                    b.ToTable("SubstitutionRules", "ingredients");
                });

            modelBuilder.Entity("SpecPour.Modules.Ingredients.Domain.Ingredient", b =>
                {
                    b.HasOne("SpecPour.Modules.Ingredients.Domain.IngredientCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpecPour.Modules.Ingredients.Domain.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SpecPour.Modules.Ingredients.Domain.IngredientAllergen", b =>
                {
                    b.HasOne("SpecPour.Modules.Ingredients.Domain.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpecPour.Modules.Ingredients.Domain.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Ingredients.Domain.SubstitutionRule", b =>
                {
                    b.HasOne("SpecPour.Modules.Ingredients.Domain.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("FromIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecPour.Modules.Ingredients.Domain.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("ToIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
