// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using SpecPour.Modules.Glossary.Infrastructure;

#nullable disable

namespace SpecPour.Modules.Glossary.Infrastructure.Migrations
{
    [DbContext(typeof(GlossaryDbContext))]
    [Migration("20260711183809_InitialGlossary")]
    partial class InitialGlossary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("glossary")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpecPour.BuildingBlocks.Events.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "outbox", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("specpour_immutable_to_tsvector_english(coalesce(\"Title\", '') || ' ' || coalesce(\"Body\", ''))", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Articles", "glossary");
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.ArticleContentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentType", "ContentId");

                    b.HasIndex("ArticleId", "ContentType", "ContentId")
                        .IsUnique();

                    b.ToTable("ArticleContentLinks", "glossary");
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.ArticleTermLink", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlossaryTermId")
                        .HasColumnType("uuid");

                    b.HasKey("ArticleId", "GlossaryTermId");

                    b.HasIndex("GlossaryTermId");

                    b.ToTable("ArticleTermLinks", "glossary");
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.GlossaryTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Definitions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("specpour_immutable_to_tsvector_english(coalesce(\"Term\", '') || ' ' || coalesce(specpour_immutable_array_to_string(\"Definitions\", ' '), ''))", true);

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Term")
                        .IsUnique();

                    b.ToTable("GlossaryTerms", "glossary");
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.GlossaryTermContentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<Guid>("GlossaryTermId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentType", "ContentId");

                    b.HasIndex("GlossaryTermId", "ContentType", "ContentId")
                        .IsUnique();

                    b.ToTable("GlossaryTermContentLinks", "glossary");
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.LinkOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TermId");

                    b.HasIndex("Context", "TermId")
                        .IsUnique();

                    b.ToTable("LinkOverrides", "glossary");
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.ArticleContentLink", b =>
                {
                    b.HasOne("SpecPour.Modules.Glossary.Domain.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.ArticleTermLink", b =>
                {
                    b.HasOne("SpecPour.Modules.Glossary.Domain.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecPour.Modules.Glossary.Domain.GlossaryTerm", null)
                        .WithMany()
                        .HasForeignKey("GlossaryTermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.GlossaryTermContentLink", b =>
                {
                    b.HasOne("SpecPour.Modules.Glossary.Domain.GlossaryTerm", null)
                        .WithMany()
                        .HasForeignKey("GlossaryTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Glossary.Domain.LinkOverride", b =>
                {
                    b.HasOne("SpecPour.Modules.Glossary.Domain.GlossaryTerm", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
