// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SpecPour.Tests.Acceptance.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class US1_SearchReconciliationT155AmendedFR_049FR_050FR_014AFeature : object, global::Xunit.IClassFixture<US1_SearchReconciliationT155AmendedFR_049FR_050FR_014AFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "US1 - Search reconciliation (T155, amended FR-049/FR-050/FR-014a)", @"  Backend half of the 2026-07-12 human review reconciling specification-statement.md
  §13/§2: a recipe's search document must include ingredient names (so searching an
  ingredient surfaces recipes using it, not only recipes named for it), a
  hierarchy-aware ""uses:<ingredient>"" facet on GET /recipes and /search, and the
  FR-014a ingredient->recipes bidirectional surface (GET /ingredients/{id}/recipes).
  Architecture (event-maintained search document) approved by John, recorded as
  ADR-0002; this feature covers its riders — the rename-refresh acceptance test and
  the ""uses"" facet's hierarchy-aware matching. Step wording throughout is
  deliberately distinct from US01DiscoverRecipesSteps' phrasing (the Reqnroll
  cross-binding-state trap — identical step text defined in two [Binding] classes
  either throws AmbiguousBindingException or silently reads the wrong class's state).", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "US01_SearchReconciliation.feature"
#line hidden
        
        public US1_SearchReconciliationT155AmendedFR_049FR_050FR_014AFeature(US1_SearchReconciliationT155AmendedFR_049FR_050FR_014AFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 14
  #line hidden
#line 15
    await testRunner.GivenAsync("the curated library contains a Rum ingredient class with a Jamaican Rum child, a " +
                    "T155 Mai Tai recipe using it, and a T155 Old Fashioned recipe using an unrelated" +
                    " Bourbon", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/US01_SearchReconciliation.feature.ndjson", 7);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="1 - A recipe\'s search document includes its ingredient names, not only its own na" +
            "me")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Search reconciliation (T155, amended FR-049/FR-050/FR-014a)")]
        [global::Xunit.TraitAttribute("Description", "1 - A recipe\'s search document includes its ingredient names, not only its own na" +
            "me")]
        public async global::System.Threading.Tasks.Task _1_ARecipesSearchDocumentIncludesItsIngredientNamesNotOnlyItsOwnName()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("1 - A recipe\'s search document includes its ingredient names, not only its own na" +
                    "me", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
  await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.WhenAsync("I look up \"Jamaican\" in the recipe search", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("the matching recipes include \"T155 Mai Tai\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="2 - The hierarchy-aware \"uses\" facet on GET /recipes matches a class-level ingred" +
            "ient\'s descendants")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Search reconciliation (T155, amended FR-049/FR-050/FR-014a)")]
        [global::Xunit.TraitAttribute("Description", "2 - The hierarchy-aware \"uses\" facet on GET /recipes matches a class-level ingred" +
            "ient\'s descendants")]
        public async global::System.Threading.Tasks.Task _2_TheHierarchy_AwareUsesFacetOnGETRecipesMatchesAClass_LevelIngredientsDescendants()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2 - The hierarchy-aware \"uses\" facet on GET /recipes matches a class-level ingred" +
                    "ient\'s descendants", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
  await this.FeatureBackgroundAsync();
#line hidden
#line 22
    await testRunner.WhenAsync("I browse recipes that use the ingredient \"Rum (T155)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
    await testRunner.ThenAsync("only the recipe \"T155 Mai Tai\" is browsed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="3 - The hierarchy-aware \"uses\" facet on GET /search narrows recipe results")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Search reconciliation (T155, amended FR-049/FR-050/FR-014a)")]
        [global::Xunit.TraitAttribute("Description", "3 - The hierarchy-aware \"uses\" facet on GET /search narrows recipe results")]
        public async global::System.Threading.Tasks.Task _3_TheHierarchy_AwareUsesFacetOnGETSearchNarrowsRecipeResults()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("3 - The hierarchy-aware \"uses\" facet on GET /search narrows recipe results", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.WhenAsync("I look up \"T155\" in the recipe search filtered to ingredient \"Rum (T155)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("the matching recipes include \"T155 Mai Tai\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("the matching recipes exclude \"T155 Old Fashioned\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="4 - FR-014a: an ingredient entry surfaces the recipes that use it, hierarchy-awar" +
            "e")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Search reconciliation (T155, amended FR-049/FR-050/FR-014a)")]
        [global::Xunit.TraitAttribute("Description", "4 - FR-014a: an ingredient entry surfaces the recipes that use it, hierarchy-awar" +
            "e")]
        public async global::System.Threading.Tasks.Task _4_FR_014AAnIngredientEntrySurfacesTheRecipesThatUseItHierarchy_Aware()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("4 - FR-014a: an ingredient entry surfaces the recipes that use it, hierarchy-awar" +
                    "e", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
  await this.FeatureBackgroundAsync();
#line hidden
#line 31
    await testRunner.WhenAsync("I look up the recipes that use ingredient \"Rum (T155)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("the ingredient\'s recipe usage includes \"T155 Mai Tai\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
    await testRunner.AndAsync("the ingredient\'s recipe usage excludes \"T155 Old Fashioned\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="5 - Renaming an ingredient refreshes dependent recipes\' search documents (ADR-000" +
            "2 rider)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Search reconciliation (T155, amended FR-049/FR-050/FR-014a)")]
        [global::Xunit.TraitAttribute("Description", "5 - Renaming an ingredient refreshes dependent recipes\' search documents (ADR-000" +
            "2 rider)")]
        public async global::System.Threading.Tasks.Task _5_RenamingAnIngredientRefreshesDependentRecipesSearchDocumentsADR_0002Rider()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("5 - Renaming an ingredient refreshes dependent recipes\' search documents (ADR-000" +
                    "2 rider)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
  await this.FeatureBackgroundAsync();
#line hidden
#line 36
    await testRunner.WhenAsync("I rename the ingredient \"Ginger Liqueur (T155)\" to \"Elderflower Liqueur (T155)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("eventually looking up \"Elderflower\" in the recipe search includes \"T155 Mule\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
    await testRunner.AndAsync("eventually looking up \"Ginger Liqueur\" in the recipe search excludes \"T155 Mule\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await US1_SearchReconciliationT155AmendedFR_049FR_050FR_014AFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await US1_SearchReconciliationT155AmendedFR_049FR_050FR_014AFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
