// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SpecPour.Tests.Acceptance.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class US1_DiscoverAndFollowCuratedRecipesFeature : object, global::Xunit.IClassFixture<US1_DiscoverAndFollowCuratedRecipesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "US1 - Discover and follow curated recipes", @"  spec.md User Story 1, scenarios 1-7 (scenario 8's responsible-consumption
  messaging is covered separately by T150's extension of this feature). Failing
  first (T030): GET /recipes, /recipes/{id}, /concepts/{id}, and /search don't
  exist yet (they land in T037/T038), so every scenario below is expected to fail
  until then. Scenario 7 is the one exception — the anonymous age-gate flow it
  exercises was already built in Phase 2 (T144), so it's expected to pass today;
  it's included here because spec.md scopes it as part of US1, not because it's
  new in this checkpoint.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "US01_DiscoverRecipes.feature"
#line hidden
        
        public US1_DiscoverAndFollowCuratedRecipesFeature(US1_DiscoverAndFollowCuratedRecipesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 11
  #line hidden
#line 12
    await testRunner.GivenAsync("the curated library contains the Mai Tai, with an egg-white Flip variant, and a D" +
                    "aiquiri concept with variants", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/US01_DiscoverRecipes.feature.ndjson", 12);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="1 - Search finds a curated recipe by primary or alternate name and opens to its f" +
            "ull detail")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "1 - Search finds a curated recipe by primary or alternate name and opens to its f" +
            "ull detail")]
        public async global::System.Threading.Tasks.Task _1_SearchFindsACuratedRecipeByPrimaryOrAlternateNameAndOpensToItsFullDetail()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("1 - Search finds a curated recipe by primary or alternate name and opens to its f" +
                    "ull detail", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 15
    await testRunner.WhenAsync("I search \"Mai Tai\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("the search results include a recipe named \"Mai Tai\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
    await testRunner.WhenAsync("I request the found recipe", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
    await testRunner.ThenAsync("the recipe response includes the ordered ingredient lines, instructions, garnish," +
                        " glassware, ice spec, equipment, flavor profile, creator \"Trader Vic\", and histo" +
                        "ry", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="2 - A recipe containing egg white displays a prominent, automatically rolled-up a" +
            "llergen flag")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "2 - A recipe containing egg white displays a prominent, automatically rolled-up a" +
            "llergen flag")]
        public async global::System.Threading.Tasks.Task _2_ARecipeContainingEggWhiteDisplaysAProminentAutomaticallyRolled_UpAllergenFlag()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2 - A recipe containing egg white displays a prominent, automatically rolled-up a" +
                    "llergen flag", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
    await testRunner.WhenAsync("I request the egg-white recipe", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("the recipe response includes the rolled-up allergen \"egg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="3 - A concept page lists each variant with a differentiator and routes to its ful" +
            "l recipe")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "3 - A concept page lists each variant with a differentiator and routes to its ful" +
            "l recipe")]
        public async global::System.Threading.Tasks.Task _3_AConceptPageListsEachVariantWithADifferentiatorAndRoutesToItsFullRecipe()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("3 - A concept page lists each variant with a differentiator and routes to its ful" +
                    "l recipe", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.WhenAsync("I request the Daiquiri concept page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("the concept response lists each variant with a differentiator and a recipe id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="4 - Every recipe shows calculated ABV and standard drinks per serving")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "4 - Every recipe shows calculated ABV and standard drinks per serving")]
        public async global::System.Threading.Tasks.Task _4_EveryRecipeShowsCalculatedABVAndStandardDrinksPerServing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("4 - Every recipe shows calculated ABV and standard drinks per serving", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 29
    await testRunner.WhenAsync("I request the Mai Tai recipe", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
    await testRunner.ThenAsync("the recipe response includes a calculated ABV and standard drinks per serving", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="5 - Faceted filters return only matching recipes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "5 - Faceted filters return only matching recipes")]
        public async global::System.Threading.Tasks.Task _5_FacetedFiltersReturnOnlyMatchingRecipes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("5 - Faceted filters return only matching recipes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
    await testRunner.WhenAsync("I browse recipes filtered by family \"family.flip\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("only recipes in the \"family.flip\" family are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="6 - Guest visitors can browse and search without an account")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "6 - Guest visitors can browse and search without an account")]
        public async global::System.Threading.Tasks.Task _6_GuestVisitorsCanBrowseAndSearchWithoutAnAccount()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("6 - Guest visitors can browse and search without an account", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 37
    await testRunner.WhenAsync("I request the recipe list, the concept list, the ingredient list, the equipment l" +
                        "ist, and the glossary term list anonymously", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("every anonymous request succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="7 - An unauthenticated visitor is presented a jurisdiction-aware age gate")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "7 - An unauthenticated visitor is presented a jurisdiction-aware age gate")]
        public async global::System.Threading.Tasks.Task _7_AnUnauthenticatedVisitorIsPresentedAJurisdiction_AwareAgeGate()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("7 - An unauthenticated visitor is presented a jurisdiction-aware age gate", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.WhenAsync("I request the age gate for the \"registration\" surface", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("the age gate responds successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
    await testRunner.AndAsync("the age gate response includes a legal drinking age", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="9 - Public recipe content is served as crawlable HTML (T044, FR-004b)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "9 - Public recipe content is served as crawlable HTML (T044, FR-004b)")]
        public async global::System.Threading.Tasks.Task _9_PublicRecipeContentIsServedAsCrawlableHTMLT044FR_004B()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("9 - Public recipe content is served as crawlable HTML (T044, FR-004b)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.WhenAsync("I request the SEO page for the Mai Tai recipe", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("the SEO page responds successfully as \"text/html\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
    await testRunner.AndAsync("the SEO page contains the recipe name \"Mai Tai\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.AndAsync("the SEO page contains a meta description", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="10 - A persistent responsible-consumption message is available for recipe pages (" +
            "T150, FR-067/FR-069)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "10 - A persistent responsible-consumption message is available for recipe pages (" +
            "T150, FR-067/FR-069)")]
        public async global::System.Threading.Tasks.Task _10_APersistentResponsible_ConsumptionMessageIsAvailableForRecipePagesT150FR_067FR_069()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("10 - A persistent responsible-consumption message is available for recipe pages (" +
                    "T150, FR-067/FR-069)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 52
    await testRunner.WhenAsync("I request the responsible-consumption message for the \"recipe\" surface", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
    await testRunner.ThenAsync("the messaging response includes a message content key", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
    await testRunner.WhenAsync("I request the support resources", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("the support resources response includes at least one resource", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="11 - A concept page\'s Approved variant to a private recipe is never listed (T199," +
            " T196 standing-rule completion)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "US1 - Discover and follow curated recipes")]
        [global::Xunit.TraitAttribute("Description", "11 - A concept page\'s Approved variant to a private recipe is never listed (T199," +
            " T196 standing-rule completion)")]
        public async global::System.Threading.Tasks.Task _11_AConceptPagesApprovedVariantToAPrivateRecipeIsNeverListedT199T196Standing_RuleCompletion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("11 - A concept page\'s Approved variant to a private recipe is never listed (T199," +
                    " T196 standing-rule completion)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 58
    await testRunner.GivenAsync("a concept page with an Approved variant to a public recipe and an Approved varian" +
                        "t to a private recipe", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
    await testRunner.WhenAsync("I request that concept page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
    await testRunner.ThenAsync("the public variant is listed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 61
    await testRunner.AndAsync("the private variant is not listed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await US1_DiscoverAndFollowCuratedRecipesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await US1_DiscoverAndFollowCuratedRecipesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
