// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SpecPour.Tests.Acceptance.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TrackInventoryAndAskWhatCanIMakeFeature : object, global::Xunit.IClassFixture<TrackInventoryAndAskWhatCanIMakeFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Track Inventory and Ask \"What Can I Make?\"", "  As a signed-in user\n  I want to record what I own and see which recipes I can m" +
                "ake, including near-misses\n  So that I know what\'s ready to pour tonight and wha" +
                "t to shop for\n\n  T064 (Phase 6 entry, US4, spec.md scenarios 1-4). Failing first" +
                " per constitution\n  Principle I (ATDD, NON-NEGOTIABLE): none of the inventory en" +
                "dpoints these scenarios\n  call (POST/GET/DELETE /inventory/items, POST /inventor" +
                "y/recognize,\n  GET /inventory/makeable) are mapped yet — T066/T067/T069 build th" +
                "em. Every scenario\n  below is expected RED until then.\n\n  Match-quality ladder (" +
                "docs/specification-statement.md §2, 2026-07-19 revision):\n  exact-product > clas" +
                "s-satisfied > substitution > missing. A recipe\'s own reported\n  match quality is" +
                " the LOOSEST quality among its satisfied lines (the one match that\n  needed the " +
                "most help) — an extensible field from day one so T201\'s facet-partial\n  value sl" +
                "ots in later without a shape change.\n\n  Ratified (John, 2026-07-19): the recipe-" +
                "level match quality is a DERIVED SUMMARY,\n  never independent truth — every reci" +
                "pe entry also carries its own per-line \"lines\"\n  array (requirement as stated, t" +
                "hat line\'s own match quality, and the inventory item\n  or substitution satisfyin" +
                "g it, null when missing). T067 computes lines first and\n  folds to the aggregate" +
                "; every downstream consumer (near-miss surfacing, substitution\n  display naming " +
                "the held item, shopping\'s cheapest-completion logic, T201\'s future\n  facet-parti" +
                "al grade) needs this line-level detail, so it belongs in the shape from\n  day on" +
                "e rather than as a later breaking change.\n\n  Every read/write path below also ca" +
                "rries its own both-directions privacy proof\n  (owner/non-owner/guest) per Phase " +
                "6 entry guidance: inventory has no public/curator\n  variant at all, ever, unlike" +
                " recipes/ingredients/equipment/venues.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "US04_Inventory.feature"
#line hidden
        
        public TrackInventoryAndAskWhatCanIMakeFeature(TrackInventoryAndAskWhatCanIMakeFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/US04_Inventory.feature.ndjson", 10);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="1 - A user adds inventory by manual entry, and photo recognition degrades to a pr" +
            "e-filled manual form when it can\'t identify the bottle (spec.md scenario 1)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Track Inventory and Ask \"What Can I Make?\"")]
        [global::Xunit.TraitAttribute("Description", "1 - A user adds inventory by manual entry, and photo recognition degrades to a pr" +
            "e-filled manual form when it can\'t identify the bottle (spec.md scenario 1)")]
        public async global::System.Threading.Tasks.Task _1_AUserAddsInventoryByManualEntryAndPhotoRecognitionDegradesToAPre_FilledManualFormWhenItCantIdentifyTheBottleSpec_MdScenario1()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("1 - A user adds inventory by manual entry, and photo recognition degrades to a pr" +
                    "e-filled manual form when it can\'t identify the bottle (spec.md scenario 1)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 32
    await testRunner.GivenAsync("an inventory-tracking signed-in user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
    await testRunner.AndAsync("a curated ingredient hierarchy of \"Beefeater\" (product) under \"London Dry Gin\" (c" +
                        "lass)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.WhenAsync("the user adds \"Beefeater\" to inventory by manual entry", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
    await testRunner.ThenAsync("the item is saved in the user\'s inventory", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
    await testRunner.WhenAsync("the user submits an unrecognizable bottle photo for recognition", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("the recognition response degrades to a pre-filled manual entry form rather than f" +
                        "ailing", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="2 - A held product satisfies a recipe that specifies its class (spec.md scenario " +
            "2)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Track Inventory and Ask \"What Can I Make?\"")]
        [global::Xunit.TraitAttribute("Description", "2 - A held product satisfies a recipe that specifies its class (spec.md scenario " +
            "2)")]
        public async global::System.Threading.Tasks.Task _2_AHeldProductSatisfiesARecipeThatSpecifiesItsClassSpec_MdScenario2()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2 - A held product satisfies a recipe that specifies its class (spec.md scenario " +
                    "2)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
    await testRunner.GivenAsync("an inventory-tracking signed-in user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
    await testRunner.AndAsync("a curated ingredient hierarchy of \"Beefeater\" (product) under \"London Dry Gin\" (c" +
                        "lass)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.AndAsync("the user has \"Beefeater\" in inventory", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
    await testRunner.AndAsync("the user has a private recipe requiring \"London Dry Gin\" at the class level", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.WhenAsync("the user asks what they can make", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the recipe is listed as makeable with match quality \"class-satisfied\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
    await testRunner.AndAsync("the recipe\'s requirement for \"London Dry Gin\" is satisfied by the held \"Beefeater" +
                        "\" item", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="3 - A near-miss recipe names its missing ingredient with a substitution suggestio" +
            "n, and is not also listed as fully makeable (spec.md scenario 3)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Track Inventory and Ask \"What Can I Make?\"")]
        [global::Xunit.TraitAttribute("Description", "3 - A near-miss recipe names its missing ingredient with a substitution suggestio" +
            "n, and is not also listed as fully makeable (spec.md scenario 3)")]
        public async global::System.Threading.Tasks.Task _3_ANear_MissRecipeNamesItsMissingIngredientWithASubstitutionSuggestionAndIsNotAlsoListedAsFullyMakeableSpec_MdScenario3()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("3 - A near-miss recipe names its missing ingredient with a substitution suggestio" +
                    "n, and is not also listed as fully makeable (spec.md scenario 3)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
    await testRunner.GivenAsync("an inventory-tracking signed-in user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
    await testRunner.AndAsync("a curated ingredient hierarchy of \"Beefeater\" (product) under \"London Dry Gin\" (c" +
                        "lass)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("the user has \"Beefeater\" in inventory", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
    await testRunner.AndAsync("the user has a private recipe requiring \"London Dry Gin\" and a second ingredient " +
                        "the user does not own", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
    await testRunner.WhenAsync("the user asks what they can make", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
    await testRunner.ThenAsync("the recipe is listed as a near-miss naming the missing ingredient", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 55
    await testRunner.AndAsync("the recipe does not also appear in the fully-makeable list", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.AndAsync("the near-miss recipe\'s lines show the \"London Dry Gin\" requirement satisfied by t" +
                        "he held \"Beefeater\" item and the second requirement missing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="4 - An inventory item displays its tracked quantity and bottle size (spec.md scen" +
            "ario 4)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Track Inventory and Ask \"What Can I Make?\"")]
        [global::Xunit.TraitAttribute("Description", "4 - An inventory item displays its tracked quantity and bottle size (spec.md scen" +
            "ario 4)")]
        public async global::System.Threading.Tasks.Task _4_AnInventoryItemDisplaysItsTrackedQuantityAndBottleSizeSpec_MdScenario4()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("4 - An inventory item displays its tracked quantity and bottle size (spec.md scen" +
                    "ario 4)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
    await testRunner.GivenAsync("an inventory-tracking signed-in user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
    await testRunner.AndAsync("a curated ingredient hierarchy of \"Beefeater\" (product) under \"London Dry Gin\" (c" +
                        "lass)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.AndAsync("the user has \"Beefeater\" in inventory with quantity 750 and bottle size \"750ml\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.WhenAsync("the user views their inventory", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("the item displays the tracked quantity and bottle size", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="5 - An empty inventory does not near-miss every recipe indiscriminately (T064 edg" +
            "e case: near-miss thresholds don\'t list everything)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Track Inventory and Ask \"What Can I Make?\"")]
        [global::Xunit.TraitAttribute("Description", "5 - An empty inventory does not near-miss every recipe indiscriminately (T064 edg" +
            "e case: near-miss thresholds don\'t list everything)")]
        public async global::System.Threading.Tasks.Task _5_AnEmptyInventoryDoesNotNear_MissEveryRecipeIndiscriminatelyT064EdgeCaseNear_MissThresholdsDontListEverything()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("5 - An empty inventory does not near-miss every recipe indiscriminately (T064 edg" +
                    "e case: near-miss thresholds don\'t list everything)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 66
    await testRunner.GivenAsync("an inventory-tracking signed-in user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 67
    await testRunner.AndAsync("a curated ingredient hierarchy of \"Beefeater\" (product) under \"London Dry Gin\" (c" +
                        "lass)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
    await testRunner.AndAsync("the user has a private recipe requiring \"London Dry Gin\" and a second ingredient " +
                        "the user does not own", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
    await testRunner.AndAsync("the user\'s inventory is empty", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.WhenAsync("the user asks what they can make", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("the recipe does not appear in the fully-makeable list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
    await testRunner.AndAsync("the recipe does not appear in the near-miss list", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="6 - Inventory is invisible to a second user, both reading and writing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Track Inventory and Ask \"What Can I Make?\"")]
        [global::Xunit.TraitAttribute("Description", "6 - Inventory is invisible to a second user, both reading and writing")]
        public async global::System.Threading.Tasks.Task _6_InventoryIsInvisibleToASecondUserBothReadingAndWriting()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("6 - Inventory is invisible to a second user, both reading and writing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
    await testRunner.GivenAsync("an inventory-tracking signed-in user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
    await testRunner.AndAsync("a curated ingredient hierarchy of \"Beefeater\" (product) under \"London Dry Gin\" (c" +
                        "lass)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.AndAsync("the user has \"Beefeater\" in inventory", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.AndAsync("a second, unrelated signed-in user", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
    await testRunner.WhenAsync("the second user requests the first user\'s inventory item directly", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
    await testRunner.ThenAsync("the item is not accessible to the second user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 81
    await testRunner.WhenAsync("the second user attempts to delete the first user\'s inventory item", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
    await testRunner.ThenAsync("the deletion is not permitted for the second user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="7 - Inventory is invisible to a guest")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Track Inventory and Ask \"What Can I Make?\"")]
        [global::Xunit.TraitAttribute("Description", "7 - Inventory is invisible to a guest")]
        public async global::System.Threading.Tasks.Task _7_InventoryIsInvisibleToAGuest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("7 - Inventory is invisible to a guest", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 84
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 85
    await testRunner.WhenAsync("an anonymous guest requests the inventory list", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
    await testRunner.ThenAsync("the request is rejected as unauthenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
    await testRunner.WhenAsync("an anonymous guest requests what can be made", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
    await testRunner.ThenAsync("the request is rejected as unauthenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="8 - Inventory items never appear in search results")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Track Inventory and Ask \"What Can I Make?\"")]
        [global::Xunit.TraitAttribute("Description", "8 - Inventory items never appear in search results")]
        public async global::System.Threading.Tasks.Task _8_InventoryItemsNeverAppearInSearchResults()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("8 - Inventory items never appear in search results", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 90
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 91
    await testRunner.GivenAsync("an inventory-tracking signed-in user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 92
    await testRunner.AndAsync("a curated ingredient hierarchy of \"Beefeater\" (product) under \"London Dry Gin\" (c" +
                        "lass)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
    await testRunner.AndAsync("the user has \"Beefeater\" in inventory", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
    await testRunner.WhenAsync("the user searches for \"Beefeater\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
    await testRunner.ThenAsync("the search results do not include an inventory entity type", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await TrackInventoryAndAskWhatCanIMakeFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await TrackInventoryAndAskWhatCanIMakeFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
