// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpecPour.Modules.Measurements.Infrastructure;

#nullable disable

namespace SpecPour.Modules.Measurements.Infrastructure.Migrations
{
    [DbContext(typeof(MeasurementsDbContext))]
    [Migration("20260711141949_InitialMeasurements")]
    partial class InitialMeasurements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("measurements")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpecPour.BuildingBlocks.Events.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "outbox", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Measurements.Domain.ConventionTable", b =>
                {
                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Version"));

                    b.Property<bool>("Effective")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Version");

                    b.ToTable("ConventionTables", "measurements");

                    b.HasData(
                        new
                        {
                            Version = 1,
                            Effective = true,
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Notes = "R14 seed values: dash/barspoon ml equivalences, stirred/shaken/built dilution midpoints, default standard-drink grams. Curator-adjustable via a new version row."
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Measurements.Domain.MethodDilution", b =>
                {
                    b.Property<int>("ConventionTableVersion")
                        .HasColumnType("integer");

                    b.Property<string>("MethodKey")
                        .HasColumnType("text");

                    b.Property<decimal>("DilutionPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("ConventionTableVersion", "MethodKey");

                    b.ToTable("MethodDilutions", "measurements");

                    b.HasData(
                        new
                        {
                            ConventionTableVersion = 1,
                            MethodKey = "stirred",
                            DilutionPercentage = 0.225m,
                            MaxPercentage = 0.25m,
                            MinPercentage = 0.20m
                        },
                        new
                        {
                            ConventionTableVersion = 1,
                            MethodKey = "shaken",
                            DilutionPercentage = 0.275m,
                            MaxPercentage = 0.30m,
                            MinPercentage = 0.25m
                        },
                        new
                        {
                            ConventionTableVersion = 1,
                            MethodKey = "built",
                            DilutionPercentage = 0m,
                            MaxPercentage = 0m,
                            MinPercentage = 0m
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Measurements.Domain.StandardDrinkGramValue", b =>
                {
                    b.Property<int>("ConventionTableVersion")
                        .HasColumnType("integer");

                    b.Property<string>("JurisdictionCode")
                        .HasColumnType("text");

                    b.Property<decimal>("GramsPerStandardDrink")
                        .HasColumnType("numeric");

                    b.HasKey("ConventionTableVersion", "JurisdictionCode");

                    b.ToTable("StandardDrinkGramValues", "measurements");

                    b.HasData(
                        new
                        {
                            ConventionTableVersion = 1,
                            JurisdictionCode = "default",
                            GramsPerStandardDrink = 14m
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Measurements.Domain.UnitEquivalence", b =>
                {
                    b.Property<int>("ConventionTableVersion")
                        .HasColumnType("integer");

                    b.Property<string>("UnitKey")
                        .HasColumnType("text");

                    b.Property<decimal>("MilliliterValue")
                        .HasColumnType("numeric");

                    b.HasKey("ConventionTableVersion", "UnitKey");

                    b.ToTable("UnitEquivalences", "measurements");

                    b.HasData(
                        new
                        {
                            ConventionTableVersion = 1,
                            UnitKey = "dash",
                            MilliliterValue = 0.92m
                        },
                        new
                        {
                            ConventionTableVersion = 1,
                            UnitKey = "barspoon",
                            MilliliterValue = 5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
