// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpecPour.Modules.Compliance.Infrastructure;

#nullable disable

namespace SpecPour.Modules.Compliance.Infrastructure.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    partial class ComplianceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compliance")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpecPour.BuildingBlocks.Events.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "outbox", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Compliance.Domain.JurisdictionRule", b =>
                {
                    b.Property<string>("JurisdictionCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LegalDrinkingAge")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JurisdictionCode");

                    b.ToTable("JurisdictionRules", "compliance");

                    b.HasData(
                        new
                        {
                            JurisdictionCode = "default",
                            EffectiveAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LegalDrinkingAge = 21,
                            Source = "Operator-configured strictest-rule default pending per-jurisdiction legal review"
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Compliance.Domain.SurfaceGateConfig", b =>
                {
                    b.Property<string>("SurfaceKey")
                        .HasColumnType("text");

                    b.Property<int>("Strictness")
                        .HasColumnType("integer");

                    b.HasKey("SurfaceKey");

                    b.ToTable("SurfaceGateConfigs", "compliance");
                });
#pragma warning restore 612, 618
        }
    }
}
