// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using SpecPour.Modules.Catalog.Infrastructure;

#nullable disable

namespace SpecPour.Modules.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpecPour.BuildingBlocks.Events.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "outbox", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.ToTable("Categories", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.ConceptPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConceptPages", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.ConceptVariantLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<string>("DifferentiatorText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("ConceptId", "RecipeId")
                        .IsUnique();

                    b.ToTable("ConceptVariantLinks", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentFamilyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.HasIndex("ParentFamilyId");

                    b.ToTable("Families", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            Definition = "The base cocktail family.",
                            NameKey = "family.cocktail"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            Definition = "Spirit-forward, stirred drinks.",
                            NameKey = "family.spiritForward"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            Definition = "Spirit, citrus, sweetener.",
                            NameKey = "family.sour"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            Definition = "Spirit lengthened with a mixer over ice.",
                            NameKey = "family.highball"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            Definition = "Wine or spirit, sugar, and fruit over crushed ice.",
                            NameKey = "family.cobbler"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            Definition = "Cobbler subtype: spirit, sugar, and mint over crushed ice.",
                            NameKey = "family.julep",
                            ParentFamilyId = new Guid("00000000-0000-0000-0000-000000000105")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            Definition = "Cobbler subtype: spirit, sugar, and muddled fruit/herbs over crushed ice.",
                            NameKey = "family.smash",
                            ParentFamilyId = new Guid("00000000-0000-0000-0000-000000000105")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000108"),
                            Definition = "Spirit or wine, sugar, and a whole egg, shaken.",
                            NameKey = "family.flip"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            Definition = "Flip subtype: served over ice with milk or cream.",
                            NameKey = "family.nog",
                            ParentFamilyId = new Guid("00000000-0000-0000-0000-000000000108")
                        });
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.FlavorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.ToTable("FlavorProfiles", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AlternateNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorAttribution")
                        .HasColumnType("text");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Garnishes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("History")
                        .HasColumnType("text");

                    b.Property<string>("IceSpec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Instructions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("LibraryScope")
                        .HasColumnType("integer");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchDocumentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("specpour_immutable_to_tsvector_english(coalesce(\"SearchDocumentText\", ''))", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PrimaryName");

                    b.ToTable("Recipes", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeCategory", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RecipeCategories", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeEquipment", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("RecipeEquipment", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeFlavorProfile", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlavorProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "FlavorProfileId");

                    b.HasIndex("FlavorProfileId");

                    b.ToTable("RecipeFlavorProfiles", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeGlassware", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("RecipeGlassware", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeIngredientLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScalingRule")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Position")
                        .IsUnique();

                    b.ToTable("RecipeIngredientLines", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeRelation", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelatedRecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecipeId", "RelatedRecipeId");

                    b.HasIndex("RelatedRecipeId");

                    b.ToTable("RecipeRelations", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTags", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Tags", "catalog");
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.ConceptVariantLink", b =>
                {
                    b.HasOne("SpecPour.Modules.Catalog.Domain.ConceptPage", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecPour.Modules.Catalog.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.Family", b =>
                {
                    b.HasOne("SpecPour.Modules.Catalog.Domain.Family", null)
                        .WithMany()
                        .HasForeignKey("ParentFamilyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeCategory", b =>
                {
                    b.HasOne("SpecPour.Modules.Catalog.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpecPour.Modules.Catalog.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeEquipment", b =>
                {
                    b.HasOne("SpecPour.Modules.Catalog.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeFlavorProfile", b =>
                {
                    b.HasOne("SpecPour.Modules.Catalog.Domain.FlavorProfile", null)
                        .WithMany()
                        .HasForeignKey("FlavorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpecPour.Modules.Catalog.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeGlassware", b =>
                {
                    b.HasOne("SpecPour.Modules.Catalog.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeIngredientLine", b =>
                {
                    b.HasOne("SpecPour.Modules.Catalog.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeRelation", b =>
                {
                    b.HasOne("SpecPour.Modules.Catalog.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecPour.Modules.Catalog.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RelatedRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecPour.Modules.Catalog.Domain.RecipeTag", b =>
                {
                    b.HasOne("SpecPour.Modules.Catalog.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecPour.Modules.Catalog.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
